 services:
  aipan-netdisk-search:
    image: unilei/aipan-netdisk-search:latest # 如果你想从 Docker Hub 获取镜像，可以使用这一行
    container_name: aipan-netdisk-search-app
    restart: always # 确保容器在停止后自动重启
    build:
      context: . # 构建上下文，通常是 Dockerfile 所在的目录
      dockerfile: Dockerfile # Dockerfile 的名称
      args:
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        JWT_SECRET: ${JWT_SECRET}
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_SCHEMA: ${DATABASE_SCHEMA}
        
    ports:
      - "3000:3000" # 映射容器的 3000 端口到宿主机的 3000 端口
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NUXT_ADMIN_USER=${ADMIN_USER}
      - NUXT_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NUXT_ADMIN_EMAIL=${ADMIN_EMAIL}
      - NUXT_JWT_SECRET=${JWT_SECRET}
      - NUXT_DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - NUXT_DATABASE_URL=${DATABASE_URL}
      - NUXT_PUBLIC_GITHUB_OWNER=${NUXT_PUBLIC_GITHUB_OWNER}
      - NUXT_PUBLIC_GITHUB_REPO=${NUXT_PUBLIC_GITHUB_REPO}
      - NUXT_PUBLIC_GITHUB_TOKEN=${NUXT_PUBLIC_GITHUB_TOKEN}
      - NUXT_PUBLIC_GITHUB_BRANCH=${NUXT_PUBLIC_GITHUB_BRANCH}
    depends_on:
      - prisma-migrate

  prisma-migrate:
    image: node:20.18.0-alpine
    container_name: aipan-netdisk-search-migrate
    command: >
      sh -c '
      npm install prisma --no-save &&
      if ! npx prisma migrate status | grep -q "Database schema is up to date"; then
        echo "Running database migrations..." &&
        npx prisma migrate deploy
      else
        echo "Database schema is already up to date, skipping migrations."
      fi
      '
    working_dir: /app
    volumes:
      - ./prisma:/app/prisma
      - ./.env:/app/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: "no"
